# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('upload', models.FileField(upload_to='uploads/')),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
